# Generated by Django 4.1.7 on 2023-12-12 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repayment',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='status',
        ),
        migrations.AddField(
            model_name='loan',
            name='state',
            field=models.CharField(default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer'),
        ),
    ]
